format : update formatter

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-yarn lint-staged
+echo 'Styling ,testing and building project before committing.'
+
+yarn lint-staged || (
+    echo 'Failed lint-staged check. Make the required changes listed above, add changes and try to commit again.'
+    false;
+
+)
+
+echo 'Code styling check pass.Trying to build now.'
 
